services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
    - "443:443"
    environment:
    - NGINX_HOST=localhost
    - NGINX_PORT=443

networks:
  app_net:
    driver: bridge